version: '3.4'

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: 369
      POSTGRES_DB: Editora
    ports:
      - "5432:5432"

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=mydatabase;Username=Admin;Password=369
    ports:
      - "5000:80"
    depends_on:
      - postgres
